version: 2.1
jobs:
  pgbench:
    docker:
      - image: buildpack-deps:buster
    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:5b:db:88:e2:e4:00:87:bc:55:c2:11:52:67:d9:0d"
      - run:
          command: |
            cd ./azure
            ./citus-bot.sh citusbot_pgbench_test_resource_group
          name: install dependencies and run pgbench tests
          no_output_timeout: 10m  
          
  scale:
    docker:
      - image: buildpack-deps:buster
    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:5b:db:88:e2:e4:00:87:bc:55:c2:11:52:67:d9:0d"
      - run:
          command: |
            cd ./azure
            ./citus-bot.sh citusbot_scale_test_resource_group
          name: install dependencies and run scale tests
          no_output_timeout: 10m
  
  tpch:
    docker:
      - image: buildpack-deps:buster
    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:5b:db:88:e2:e4:00:87:bc:55:c2:11:52:67:d9:0d"
      - run:
          command: |
            cd ./azure
            ./citus-bot.sh citusbot_tpch_test_resource_group
          name: install dependencies and run tpch tests
          no_output_timeout: 10m   

  delete_resource_group:
    docker:
      - image: buildpack-deps:buster
    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - run:
          command: |
            cd ./azure
            ./delete-resource-group-job.sh
          name: delete the given resource group
          no_output_timeout: 10m             

  valgrind-multi-test:
    docker:
      - image: buildpack-deps:focal

    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:5b:db:88:e2:e4:00:87:bc:55:c2:11:52:67:d9:0d"
      - run:
          command: |
            cd ./azure
            ./citus-bot.sh citusbot_valgrind_multi_test_resource_group
          name: install dependencies and run valgrind tests (check-multi-vg)
          no_output_timeout: 10m 

  finalize-valgrind-multi-test:
    docker:
      - image: buildpack-deps:focal

    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:5b:db:88:e2:e4:00:87:bc:55:c2:11:52:67:d9:0d"
      - run:
          command: |
            cd ./azure
            ./finalize-valgrind-test.sh "citusbot_valgrind_multi_test_resource_group"
          name: finalize valgrind tests (check-multi-vg)
          no_output_timeout: 10m

  valgrind-multi-1-test:
    docker:
      - image: buildpack-deps:trusty

    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:5b:db:88:e2:e4:00:87:bc:55:c2:11:52:67:d9:0d"      
      - run:
          command: |
            cd ./azure
            ./citus-bot.sh citusbot_valgrind_multi_1_test_resource_group
          name: install dependencies and run valgrind tests (check-multi-1-vg)
          no_output_timeout: 10m       

  finalize-valgrind-multi-1-test:
    docker:
      - image: buildpack-deps:trusty

    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:5b:db:88:e2:e4:00:87:bc:55:c2:11:52:67:d9:0d"      
      - run:
          command: |
            cd ./azure
            ./finalize-valgrind-test.sh citusbot_valgrind_multi_1_test_resource_group
          name: finalize valgrind tests (check-multi-1-vg)
          no_output_timeout: 10m

  valgrind-columnar-test:
    docker:
      - image: buildpack-deps:trusty

    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:5b:db:88:e2:e4:00:87:bc:55:c2:11:52:67:d9:0d"      
      - run:
          command: |
            cd ./azure
            ./citus-bot.sh citusbot_valgrind_columnar_test_resource_group
          name: install dependencies and run valgrind tests (check-columnar-vg)
          no_output_timeout: 10m
          
  finalize-valgrind-columnar-test:
    docker:
      - image: buildpack-deps:trusty

    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:5b:db:88:e2:e4:00:87:bc:55:c2:11:52:67:d9:0d"      
      - run:
          command: |
            cd ./azure
            ./finalize-valgrind-test.sh citusbot_valgrind_columnar_test_resource_group
          name: finalize valgrind tests (check-columnar-vg)
          no_output_timeout: 10m

orbs:
  azure-cli: circleci/azure-cli@1.0.0      

workflows:
  version: 2

  cleanup:
    jobs:
      - delete_resource_group:
          filters:
            branches:
              only:
                - /delete_resource_group\/.*/ # match with delete_resource_group/ prefix

  performance-tests:
    jobs:
      - pgbench:
          filters:
            branches:
              only:
                - /pgbench\/.*/ # match with pgbench/ prefix
                - /all_performance_test\/.*/ # match with all_performance_test/ prefix
      - scale:
          filters:
            branches:
              only: 
                - /scale\/.*/ # match with scale/ prefix
                - /all_performance_test\/.*/ # match with all_performance_test/ prefix
      - tpch:
          filters:
            branches:
              only: 
                - /tpch\/.*/ # match with tpch/ prefix
                - /all_performance_test\/.*/ # match with all_performance_test/ prefix

  weekly-valgrind-multi:
    triggers:
      - schedule:
          # https://crontab.guru/#0_0_*_*_1
          cron: "45 17 * * 5"
          filters:
            branches:
              only:
                - add-another-vg
    jobs:
      - valgrind-multi-test

  weekly-valgrind-multi-finalize:
    triggers:
      - schedule:
          # https://crontab.guru/#00_6_*_*_1
          cron: "15 23 * * 5"
          filters:
            branches:
              only:
                - add-another-vg
    jobs:
      - finalize-valgrind-multi-test

  weekly-valgrind-multi-1:
    triggers:
      - schedule:
          # https://crontab.guru/#0_0_*_*_1
          cron: "45 17 * * 5"
          filters:
            branches:
              only:
                - add-another-vg
    jobs:
      - valgrind-multi-1-test

  weekly-valgrind-multi-1-finalize:
    triggers:
      - schedule:
          # https://crontab.guru/#00_12_*_*_1
          cron: "15 5 * * 6"
          filters:
            branches:
              only:
                - add-another-vg
    jobs:
      - finalize-valgrind-multi-1-test
      
  weekly-valgrind-columnar:
    triggers:
      - schedule:
          # https://crontab.guru/#0_0_*_*_1
          cron: "45 17 * * 5"
          filters:
            branches:
              only:
                - add-another-vg
    jobs:
      - valgrind-columnar-test

  weekly-valgrind-columnar-finalize:
    triggers:
      - schedule:
          # https://crontab.guru/#00_2_*_*_1
          cron: "45 19 * * 5"
          filters:
            branches:
              only:
                - add-another-vg
    jobs:
      - finalize-valgrind-columnar-test

  # the below workflows can be used during maintenance operations on the tests in this repo
  # simply uncomment the workflow you made changes to and push to a branch.
  # Don't leave these workflows uncommented when merging to main
  
  # onpush-valgrind:
  #   jobs:
  #     - valgrind-test
  # onpush-finalize-valgrind:
  #   jobs:
  #     - finalize-valgrind-test
